-- Script de création des tables nécessaires à la synchro des événements (séances de cours et examens)

CREATE TABLE HEC_EVENT_EXTRACT (
	"CATALOG_NBR" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"STRM" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"SESSION_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
	"CLASS_SECTION" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"SEQ" NUMBER NOT NULL ENABLE,
	"CLASS_EXAM_TYPE" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"DATE_HEURE_DEBUT" DATE NOT NULL ENABLE,
	"DATE_HEURE_FIN" DATE NOT NULL ENABLE,
	"FACILITY_ID" VARCHAR2(5 BYTE),
	"DESCR_FACILITY" VARCHAR2(100 BYTE),
	"DESCR" VARCHAR2(100 BYTE));

CREATE TABLE HEC_EVENT (
	"CATALOG_NBR" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"STRM" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"SESSION_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
	"CLASS_SECTION" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"SEQ" NUMBER NOT NULL ENABLE,
	"CLASS_EXAM_TYPE" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"DATE_HEURE_DEBUT" DATE NOT NULL ENABLE,
	"DATE_HEURE_FIN" DATE NOT NULL ENABLE,
	"FACILITY_ID" VARCHAR2(5 BYTE),
	"DESCR_FACILITY" VARCHAR2(100 BYTE),
	"DESCR" VARCHAR2(100 BYTE),
	"STATE" VARCHAR2(1 BYTE),
	"EVENT_ID" VARCHAR2(36 BYTE),
	 CONSTRAINT "HEC_EVENT_PK" PRIMARY KEY ("CATALOG_NBR", "STRM", "SESSION_CODE", "CLASS_SECTION", "SEQ", "CLASS_EXAM_TYPE"));
