--sessions
select * from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25');

--course offering
select * from CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25'));

--sections
select * from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')));

--enrollment set
select * from CM_ENROLLMENT_SET_T where ENTERPRISE_ID in (select CM_MEMBER_CONTAINER_T.ENTERPRISE_ID from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25'))));

--enrollment
select * from CM_ENROLLMENT_T where ENROLLMENT_SET in (select CM_ENROLLMENT_SET_T.ENROLLMENT_SET_ID from CM_ENROLLMENT_SET_T where ENTERPRISE_ID in 
(select CM_MEMBER_CONTAINER_T.ENTERPRISE_ID from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')))));

-- official instructor
select * from CM_OFFICIAL_INSTRUCTORS_T where ENROLLMENT_SET_ID in (select CM_ENROLLMENT_SET_T.ENROLLMENT_SET_ID from CM_ENROLLMENT_SET_T where ENTERPRISE_ID in 
(select CM_MEMBER_CONTAINER_T.ENTERPRISE_ID from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')))));

--membership
select * from CM_MEMBERSHIP_T where MEMBER_CONTAINER_ID in (select CM_MEMBER_CONTAINER_T.MEMBER_CONTAINER_ID from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25'))));

--cross listing
select * from CM_COURSE_SET_OFFERING_ASSOC_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')));

--membership
delete from CM_MEMBERSHIP_T where MEMBER_CONTAINER_ID in (select CM_MEMBER_CONTAINER_T.MEMBER_CONTAINER_ID from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25'))));

-- official instructor
delete from CM_OFFICIAL_INSTRUCTORS_T where ENROLLMENT_SET_ID in (select CM_ENROLLMENT_SET_T.ENROLLMENT_SET_ID from CM_ENROLLMENT_SET_T where ENTERPRISE_ID in 
(select CM_MEMBER_CONTAINER_T.ENTERPRISE_ID from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')))));

--enrollment
delete from CM_ENROLLMENT_T where ENROLLMENT_SET in (select CM_ENROLLMENT_SET_T.ENROLLMENT_SET_ID from CM_ENROLLMENT_SET_T where ENTERPRISE_ID in 
(select CM_MEMBER_CONTAINER_T.ENTERPRISE_ID from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')))));

--sections
delete from CM_MEMBER_CONTAINER_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')));

--enrollment set
delete from CM_ENROLLMENT_SET_T where COURSE_OFFERING in (select CM_MEMBER_CONTAINER_T.MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')));

--cross listing
delete from CM_COURSE_SET_OFFERING_ASSOC_T where COURSE_OFFERING in (select MEMBER_CONTAINER_ID from 
CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25')));

--course offering
delete from CM_MEMBER_CONTAINER_T where ACADEMIC_SESSION in (select CM_ACADEMIC_SESSION_T.ACADEMIC_SESSION_ID from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25'));

--sessions
delete from CM_ACADEMIC_SESSION_T where START_DATE > to_date('17-08-25');


